# Nivel 0
NO_TEMPORAL = 0
TEMPORAL_N_HORAS = 1
TEMPORAL_ANTES_N_HORAS = 2

# Nivel 1
FASE_SIN_ALERTA = 0
FASE_EN_ALERTA = 1

# Nivel 2
FASE_NO_COMENZADA = -1
FASE_PROTEGIDA_POR_ESTRUCTURA = 0
FASE_EN_PROCESO_PROTECCION = 1
FASE_SIN_PROTECCION = 2
FASE_PARADA_INVERNAL = 3

# Nivel 3
FASE_NO_TRABAJA = -1
FASE_NO_TOCA_TRABAJAR = 0
FASE_NO_TRABAJA_RESTRICCION = 1
FASE_NO_TRABAJA_OPERATIVIDAD = 2
FASE_TRABAJA = 3
FASE_TRABAJA_RETRASADA = 4
FASE_PROTEGIENDO = 5
FASE_PERDIDAS = 6
FASE_ACABADA = 7
