CICLO_CALMA = 0
CICLO_SOLICITACION = 1

MODO_NO_TIENE_AVERIA = 0
MODO_TIENE_AVERIA = 1
MODO_TIENE_DESTRUCCION_TOTAL = 2

MODO_NO_REPARA = 0
MODO_ESPERANDO_PARA_EMPEZAR_REPARAR = 1
MODO_NO_REPARA_OPERATIVIDAD = 2
MODO_REPARANDO = 3
MODO_FINALIZA_REPARACION = 4
MODO_SALE_DE_INICIO_DE_AVERIA = 5
MODO_SUFRE_DANNOS = 6
MODO_NO_ALCANZA_INICIO_AVERIA_NO_SUFRE_DANNOS = 7
MODO_SUFRE_DESTRUCCION_TOTAL = 8
MODO_SALE_DE_DESTRUCCION_TOTAL = 9


MODO_UTILIZA_ELEMENTO_PUERTO_REPARACION = 0
MODO_CONTRATA_ELEMENTO_REPARACION = 1
